services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    # volumes:
    #   - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - buenaNetwork
  metabase:
    image: metabase/metabase:latest
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - buenaNetwork

networks:
  buenaNetwork:
    driver: bridge